-- =============================================================================
-- Sentinel — Supabase PostgreSQL Schema
-- =============================================================================
-- Run this entire file in:
--   Supabase Dashboard → your project → SQL Editor → New Query → Run
--
-- BIGINT PKs are intentional: Sentinel upserts rows using the same numeric IDs
-- generated by local SQLite, so BIGSERIAL / GENERATED ALWAYS would conflict.
--
-- Timestamps are Unix epoch milliseconds stored as BIGINT (matching SQLite).
--
-- Cascade behaviour:
--   Deleting a target removes ALL of their data automatically via FK cascades.
--   Deleting an alert rule nullifies its rule_id in alert_history (history is
--   preserved for audit purposes even after the rule is removed).
-- =============================================================================


-- =============================================================================
-- EXTENSION
-- =============================================================================

-- pg_trgm enables fast ILIKE / full-text search on message content if needed.
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- =============================================================================
-- CORE: targets
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.targets (
    user_id  TEXT    PRIMARY KEY,
    added_at BIGINT  NOT NULL,
    label    TEXT,
    notes    TEXT,
    priority INTEGER NOT NULL DEFAULT 0,
    active   INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT targets_priority_non_negative CHECK (priority >= 0),
    CONSTRAINT targets_active_bool           CHECK (active IN (0, 1))
);

COMMENT ON TABLE  public.targets            IS 'Tracked Discord user accounts.';
COMMENT ON COLUMN public.targets.user_id    IS 'Discord snowflake ID (17-20 digit string).';
COMMENT ON COLUMN public.targets.added_at   IS 'Unix epoch ms when the target was added.';
COMMENT ON COLUMN public.targets.active     IS '1 = actively tracked, 0 = paused.';


-- =============================================================================
-- EVENTS — append-only timeline for every observed event
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.events (
    id         BIGINT  PRIMARY KEY,
    target_id  TEXT    NOT NULL,
    event_type TEXT    NOT NULL,
    timestamp  BIGINT  NOT NULL,
    data       TEXT    NOT NULL,   -- JSON blob
    guild_id   TEXT,
    channel_id TEXT,

    CONSTRAINT fk_events_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

COMMENT ON TABLE  public.events            IS 'Append-only log of every observable Discord event.';
COMMENT ON COLUMN public.events.data       IS 'JSON payload specific to each event_type.';
COMMENT ON COLUMN public.events.timestamp  IS 'Unix epoch ms when the event occurred.';

CREATE INDEX IF NOT EXISTS idx_events_target
    ON public.events (target_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_type
    ON public.events (event_type, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_timestamp
    ON public.events (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_guild
    ON public.events (guild_id, timestamp DESC)   WHERE guild_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_events_channel
    ON public.events (channel_id, timestamp DESC) WHERE channel_id IS NOT NULL;


-- =============================================================================
-- PROFILE SNAPSHOTS — point-in-time profile captures
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.profile_snapshots (
    id                 BIGINT  PRIMARY KEY,
    target_id          TEXT    NOT NULL,
    timestamp          BIGINT  NOT NULL,
    username           TEXT,
    global_name        TEXT,
    discriminator      TEXT,
    avatar_hash        TEXT,
    banner_hash        TEXT,
    bio                TEXT,
    pronouns           TEXT,
    accent_color       INTEGER,
    connected_accounts TEXT,   -- JSON array
    mutual_guilds      TEXT,   -- JSON array

    CONSTRAINT fk_profile_snapshots_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

COMMENT ON TABLE  public.profile_snapshots                   IS 'Immutable snapshots of a target''s Discord profile over time.';
COMMENT ON COLUMN public.profile_snapshots.connected_accounts IS 'JSON array of {type, id, name, verified, visibility}.';
COMMENT ON COLUMN public.profile_snapshots.mutual_guilds      IS 'JSON array of {id, nick} for shared servers.';

CREATE INDEX IF NOT EXISTS idx_snapshots_target
    ON public.profile_snapshots (target_id, timestamp DESC);


-- =============================================================================
-- PRESENCE SESSIONS — online/idle/dnd/offline windows
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.presence_sessions (
    id          BIGINT  PRIMARY KEY,
    target_id   TEXT    NOT NULL,
    status      TEXT    NOT NULL,
    platform    TEXT,                -- 'desktop' | 'mobile' | 'web' | NULL
    start_time  BIGINT  NOT NULL,
    end_time    BIGINT,
    duration_ms BIGINT,

    CONSTRAINT fk_presence_sessions_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT presence_status_valid
        CHECK (status IN ('online', 'idle', 'dnd', 'offline', 'unknown')),
    CONSTRAINT presence_duration_positive
        CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT presence_end_after_start
        CHECK (end_time IS NULL OR end_time >= start_time)
);

COMMENT ON TABLE  public.presence_sessions             IS 'Continuous windows of a specific status (online/idle/dnd/offline).';
COMMENT ON COLUMN public.presence_sessions.duration_ms IS 'end_time - start_time in ms; NULL while the session is still open.';

CREATE INDEX IF NOT EXISTS idx_presence_target
    ON public.presence_sessions (target_id, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_presence_open
    ON public.presence_sessions (target_id)
    WHERE end_time IS NULL;


-- =============================================================================
-- ACTIVITY SESSIONS — games, Spotify, streaming, custom status
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.activity_sessions (
    id             BIGINT  PRIMARY KEY,
    target_id      TEXT    NOT NULL,
    activity_name  TEXT    NOT NULL,
    activity_type  INTEGER NOT NULL,   -- Discord activity type (0=game, 2=spotify, etc.)
    application_id TEXT,
    details        TEXT,
    state          TEXT,
    start_time     BIGINT  NOT NULL,
    end_time       BIGINT,
    duration_ms    BIGINT,
    metadata       TEXT,               -- JSON (assets, timestamps, party, …)

    CONSTRAINT fk_activity_sessions_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT activity_duration_positive
        CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT activity_end_after_start
        CHECK (end_time IS NULL OR end_time >= start_time)
);

COMMENT ON TABLE  public.activity_sessions              IS 'Continuous windows of a Discord rich-presence activity.';
COMMENT ON COLUMN public.activity_sessions.activity_type IS '0=Playing, 1=Streaming, 2=Listening, 3=Watching, 4=Custom, 5=Competing.';
COMMENT ON COLUMN public.activity_sessions.metadata      IS 'Raw JSON from Discord: assets, timestamps, party, buttons, etc.';

CREATE INDEX IF NOT EXISTS idx_activity_target
    ON public.activity_sessions (target_id, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_activity_name
    ON public.activity_sessions (activity_name, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_activity_type
    ON public.activity_sessions (target_id, activity_type, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_activity_open
    ON public.activity_sessions (target_id)
    WHERE end_time IS NULL;


-- =============================================================================
-- VOICE SESSIONS — time spent in voice channels
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.voice_sessions (
    id              BIGINT  PRIMARY KEY,
    target_id       TEXT    NOT NULL,
    guild_id        TEXT    NOT NULL,
    channel_id      TEXT    NOT NULL,
    channel_name    TEXT,
    start_time      BIGINT  NOT NULL,
    end_time        BIGINT,
    duration_ms     BIGINT,
    self_mute       INTEGER NOT NULL DEFAULT 0,
    self_deaf       INTEGER NOT NULL DEFAULT 0,
    server_mute     INTEGER NOT NULL DEFAULT 0,
    server_deaf     INTEGER NOT NULL DEFAULT 0,
    streaming       INTEGER NOT NULL DEFAULT 0,
    co_participants TEXT,              -- JSON array of user IDs

    CONSTRAINT fk_voice_sessions_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT voice_self_mute_bool    CHECK (self_mute   IN (0, 1)),
    CONSTRAINT voice_self_deaf_bool    CHECK (self_deaf   IN (0, 1)),
    CONSTRAINT voice_server_mute_bool  CHECK (server_mute IN (0, 1)),
    CONSTRAINT voice_server_deaf_bool  CHECK (server_deaf IN (0, 1)),
    CONSTRAINT voice_streaming_bool    CHECK (streaming   IN (0, 1)),
    CONSTRAINT voice_duration_positive CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT voice_end_after_start   CHECK (end_time IS NULL OR end_time >= start_time)
);

COMMENT ON TABLE  public.voice_sessions                IS 'Continuous windows of voice channel presence.';
COMMENT ON COLUMN public.voice_sessions.co_participants IS 'JSON array of other user IDs observed in the same channel.';

CREATE INDEX IF NOT EXISTS idx_voice_target
    ON public.voice_sessions (target_id, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_voice_guild
    ON public.voice_sessions (guild_id, channel_id, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_voice_open
    ON public.voice_sessions (target_id)
    WHERE end_time IS NULL;


-- =============================================================================
-- MESSAGES — observed Discord messages
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.messages (
    message_id          TEXT    PRIMARY KEY,
    target_id           TEXT    NOT NULL,
    channel_id          TEXT    NOT NULL,
    guild_id            TEXT,
    content             TEXT,
    content_length      INTEGER,
    attachment_count    INTEGER NOT NULL DEFAULT 0,
    embed_count         INTEGER NOT NULL DEFAULT 0,
    has_sticker         INTEGER NOT NULL DEFAULT 0,
    is_reply            INTEGER NOT NULL DEFAULT 0,
    reply_to_user_id    TEXT,
    reply_to_message_id TEXT,
    created_at          BIGINT  NOT NULL,
    edited_at           BIGINT,
    deleted_at          BIGINT,
    edit_history        TEXT,    -- JSON array of previous content strings
    word_count          INTEGER,
    emoji_count         INTEGER,
    mention_count       INTEGER,
    link_count          INTEGER,

    CONSTRAINT fk_messages_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT messages_has_sticker_bool CHECK (has_sticker IN (0, 1)),
    CONSTRAINT messages_is_reply_bool    CHECK (is_reply    IN (0, 1)),
    CONSTRAINT messages_content_length   CHECK (content_length IS NULL OR content_length >= 0)
);

COMMENT ON TABLE  public.messages              IS 'Snapshot of each observed message, including edits and deletions.';
COMMENT ON COLUMN public.messages.content      IS 'Truncated to 2000 chars (Discord limit).';
COMMENT ON COLUMN public.messages.edit_history IS 'JSON array of previous content values, oldest first.';

CREATE INDEX IF NOT EXISTS idx_messages_target
    ON public.messages (target_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_channel
    ON public.messages (channel_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_deleted
    ON public.messages (target_id, deleted_at DESC) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_edited
    ON public.messages (target_id, edited_at DESC)  WHERE edited_at  IS NOT NULL;
-- Trigram index for content search (requires pg_trgm extension above)
CREATE INDEX IF NOT EXISTS idx_messages_content_trgm
    ON public.messages USING gin (content gin_trgm_ops) WHERE content IS NOT NULL;


-- =============================================================================
-- TYPING EVENTS — typing indicators (includes ghost-type detection)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.typing_events (
    id                  BIGINT  PRIMARY KEY,
    target_id           TEXT    NOT NULL,
    channel_id          TEXT    NOT NULL,
    guild_id            TEXT,
    timestamp           BIGINT  NOT NULL,
    resulted_in_message INTEGER NOT NULL DEFAULT 0,   -- 1 if a message followed
    message_delay_ms    INTEGER,                       -- ms between typing start and send

    CONSTRAINT fk_typing_events_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT typing_resulted_bool CHECK (resulted_in_message IN (0, 1)),
    CONSTRAINT typing_delay_positive CHECK (message_delay_ms IS NULL OR message_delay_ms >= 0)
);

COMMENT ON TABLE  public.typing_events                      IS 'Each TYPING_START event. resulted_in_message=0 = ghost type.';
COMMENT ON COLUMN public.typing_events.resulted_in_message  IS '0 = ghost-typed (never sent), 1 = message followed.';

CREATE INDEX IF NOT EXISTS idx_typing_target
    ON public.typing_events (target_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_typing_ghosts
    ON public.typing_events (target_id)
    WHERE resulted_in_message = 0;


-- =============================================================================
-- REACTIONS — emoji reactions added/removed by the target
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.reactions (
    id                BIGINT  PRIMARY KEY,
    target_id         TEXT    NOT NULL,
    message_id        TEXT    NOT NULL,
    message_author_id TEXT,
    channel_id        TEXT    NOT NULL,
    guild_id          TEXT,
    emoji_name        TEXT    NOT NULL,
    emoji_id          TEXT,
    is_custom         INTEGER NOT NULL DEFAULT 0,
    added_at          BIGINT  NOT NULL,
    removed_at        BIGINT,

    CONSTRAINT fk_reactions_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT reactions_is_custom_bool CHECK (is_custom IN (0, 1)),
    CONSTRAINT reactions_remove_after_add
        CHECK (removed_at IS NULL OR removed_at >= added_at)
);

COMMENT ON TABLE  public.reactions           IS 'Emoji reactions placed (or removed) by the target.';
COMMENT ON COLUMN public.reactions.is_custom IS '1 = custom server emoji, 0 = standard Unicode emoji.';

CREATE INDEX IF NOT EXISTS idx_reactions_target
    ON public.reactions (target_id, added_at DESC);
CREATE INDEX IF NOT EXISTS idx_reactions_message
    ON public.reactions (message_id);


-- =============================================================================
-- GUILD MEMBER EVENTS — nickname / role changes per server
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.guild_member_events (
    id         BIGINT  PRIMARY KEY,
    target_id  TEXT    NOT NULL,
    guild_id   TEXT    NOT NULL,
    event_type TEXT    NOT NULL,   -- NICKNAME_CHANGE | ROLE_ADD | ROLE_REMOVE | SERVER_JOIN | SERVER_LEAVE
    timestamp  BIGINT  NOT NULL,
    old_value  TEXT,
    new_value  TEXT,

    CONSTRAINT fk_guild_member_events_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

COMMENT ON TABLE  public.guild_member_events IS 'Nickname changes, role changes, and server join/leave events.';

CREATE INDEX IF NOT EXISTS idx_guild_member_target
    ON public.guild_member_events (target_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_guild_member_guild
    ON public.guild_member_events (guild_id, timestamp DESC);


-- =============================================================================
-- ALERT RULES — configurable trigger rules
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.alert_rules (
    id         BIGINT  PRIMARY KEY,
    target_id  TEXT,              -- NULL = applies to all targets (global rule)
    rule_type  TEXT    NOT NULL,
    condition  TEXT    NOT NULL,  -- JSON condition object
    enabled    INTEGER NOT NULL DEFAULT 1,
    created_at BIGINT  NOT NULL,

    -- When a specific target is deleted, remove their dedicated rules.
    -- Global rules (target_id IS NULL) are unaffected by any target deletion.
    CONSTRAINT fk_alert_rules_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT alert_rules_enabled_bool CHECK (enabled IN (0, 1))
);

COMMENT ON TABLE  public.alert_rules           IS 'Configurable alert rules. target_id=NULL means the rule applies globally.';
COMMENT ON COLUMN public.alert_rules.condition IS 'JSON: {field, operator, value, after_hour, …}.';

CREATE INDEX IF NOT EXISTS idx_alert_rules_target
    ON public.alert_rules (target_id) WHERE target_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_alert_rules_enabled
    ON public.alert_rules (enabled, rule_type);


-- =============================================================================
-- ALERT HISTORY — fired alert log
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.alert_history (
    id           BIGINT  PRIMARY KEY,
    rule_id      BIGINT,           -- SET NULL if the rule is later deleted
    target_id    TEXT    NOT NULL,
    alert_type   TEXT    NOT NULL,
    message      TEXT    NOT NULL,
    timestamp    BIGINT  NOT NULL,
    acknowledged INTEGER NOT NULL DEFAULT 0,

    -- Preserve historical fire records even if the rule is deleted.
    CONSTRAINT fk_alert_history_rule
        FOREIGN KEY (rule_id) REFERENCES public.alert_rules (id)
        ON DELETE SET NULL,

    -- But wipe history when the target is removed entirely.
    CONSTRAINT fk_alert_history_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT alert_history_acknowledged_bool CHECK (acknowledged IN (0, 1))
);

COMMENT ON TABLE  public.alert_history               IS 'Immutable log of every alert that fired. rule_id goes NULL if rule is deleted.';
COMMENT ON COLUMN public.alert_history.acknowledged  IS '1 = operator has acknowledged this alert in the UI.';

CREATE INDEX IF NOT EXISTS idx_alert_history_target
    ON public.alert_history (target_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_alert_history_unacked
    ON public.alert_history (target_id, acknowledged)
    WHERE acknowledged = 0;
CREATE INDEX IF NOT EXISTS idx_alert_history_rule
    ON public.alert_history (rule_id) WHERE rule_id IS NOT NULL;


-- =============================================================================
-- DAILY SUMMARIES — pre-aggregated per-target per-day statistics
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.daily_summaries (
    id               BIGINT  PRIMARY KEY,
    target_id        TEXT    NOT NULL,
    date             TEXT    NOT NULL,   -- 'YYYY-MM-DD'
    online_minutes   INTEGER NOT NULL DEFAULT 0,
    idle_minutes     INTEGER NOT NULL DEFAULT 0,
    dnd_minutes      INTEGER NOT NULL DEFAULT 0,
    offline_minutes  INTEGER NOT NULL DEFAULT 0,
    message_count    INTEGER NOT NULL DEFAULT 0,
    edit_count       INTEGER NOT NULL DEFAULT 0,
    delete_count     INTEGER NOT NULL DEFAULT 0,
    ghost_type_count INTEGER NOT NULL DEFAULT 0,
    voice_minutes    INTEGER NOT NULL DEFAULT 0,
    activity_minutes TEXT,              -- JSON: {"GameName": minutes, …}
    reaction_count   INTEGER NOT NULL DEFAULT 0,
    first_seen       BIGINT,            -- epoch ms of first non-offline event
    last_seen        BIGINT,            -- epoch ms of last non-offline event
    peak_hour        INTEGER,           -- 0-23 hour with most activity

    CONSTRAINT fk_daily_summaries_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT daily_summaries_unique       UNIQUE (target_id, date),
    CONSTRAINT daily_online_non_neg         CHECK (online_minutes   >= 0),
    CONSTRAINT daily_idle_non_neg           CHECK (idle_minutes     >= 0),
    CONSTRAINT daily_dnd_non_neg            CHECK (dnd_minutes      >= 0),
    CONSTRAINT daily_offline_non_neg        CHECK (offline_minutes  >= 0),
    CONSTRAINT daily_message_count_non_neg  CHECK (message_count    >= 0),
    CONSTRAINT daily_voice_non_neg          CHECK (voice_minutes    >= 0),
    CONSTRAINT daily_peak_hour_range        CHECK (peak_hour IS NULL OR (peak_hour >= 0 AND peak_hour <= 23)),
    CONSTRAINT daily_last_after_first       CHECK (last_seen IS NULL OR first_seen IS NULL OR last_seen >= first_seen)
);

COMMENT ON TABLE  public.daily_summaries                  IS 'Pre-aggregated daily statistics, recomputed hourly by the selfbot.';
COMMENT ON COLUMN public.daily_summaries.activity_minutes IS 'JSON object mapping activity name → total minutes for that day.';

CREATE INDEX IF NOT EXISTS idx_daily_target
    ON public.daily_summaries (target_id, date DESC);


-- =============================================================================
-- CONVENIENCE VIEW — total active minutes per day
-- (Mirrors the computed column in the selfbot's getDailySummaries query.)
-- =============================================================================

CREATE OR REPLACE VIEW public.daily_summaries_with_active AS
SELECT *,
       (online_minutes + idle_minutes + dnd_minutes) AS total_active_minutes
FROM public.daily_summaries;

COMMENT ON VIEW public.daily_summaries_with_active
    IS 'daily_summaries plus total_active_minutes = online + idle + dnd (offline excluded).';


-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
-- The selfbot uses the Supabase SERVICE ROLE key which bypasses RLS entirely.
-- RLS is explicitly disabled on all tables to make that intent clear and to
-- avoid any accidental policy interference from future Supabase dashboard
-- changes. If you ever expose these tables to the anon key (e.g. a public
-- dashboard), re-enable RLS and write appropriate policies.
-- =============================================================================

ALTER TABLE public.targets              DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.events               DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_snapshots    DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.presence_sessions    DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_sessions    DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_sessions       DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages             DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.typing_events        DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reactions            DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.guild_member_events  DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_rules          DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_history        DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_summaries      DISABLE ROW LEVEL SECURITY;


-- =============================================================================
-- SCHEMA v2 ADDITIONS
-- =============================================================================

-- ── alert_rules — new columns ─────────────────────────────────────────────────

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='alert_rules' AND column_name='fire_count_24h') THEN
        ALTER TABLE public.alert_rules ADD COLUMN fire_count_24h  INTEGER NOT NULL DEFAULT 0;
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='alert_rules' AND column_name='last_fire_at') THEN
        ALTER TABLE public.alert_rules ADD COLUMN last_fire_at    BIGINT;
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='alert_rules' AND column_name='auto_suppressed') THEN
        ALTER TABLE public.alert_rules ADD COLUMN auto_suppressed  INTEGER NOT NULL DEFAULT 0;
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='alert_rules' AND column_name='fatigue_threshold') THEN
        ALTER TABLE public.alert_rules ADD COLUMN fatigue_threshold INTEGER NOT NULL DEFAULT 20;
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='alert_rules' AND column_name='composite_condition') THEN
        ALTER TABLE public.alert_rules ADD COLUMN composite_condition TEXT;
    END IF;
END $$;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='alert_rules' AND column_name='digest_mode') THEN
        ALTER TABLE public.alert_rules ADD COLUMN digest_mode INTEGER NOT NULL DEFAULT 0;
    END IF;
END $$;


-- ── relationship_analysis ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.relationship_analysis (
    id                 BIGINT  PRIMARY KEY,
    target_id          TEXT    NOT NULL,
    other_user_id      TEXT    NOT NULL,
    classification     TEXT    NOT NULL,
    confidence         REAL    NOT NULL DEFAULT 0.0,
    reasoning          TEXT,
    analyzed_at        BIGINT  NOT NULL,
    data_window_start  BIGINT  NOT NULL,
    data_window_end    BIGINT  NOT NULL,

    CONSTRAINT fk_rel_analysis_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT rel_analysis_unique UNIQUE (target_id, other_user_id)
);
CREATE INDEX IF NOT EXISTS idx_rel_analysis_target
    ON public.relationship_analysis (target_id, analyzed_at DESC);

ALTER TABLE public.relationship_analysis DISABLE ROW LEVEL SECURITY;


-- ── relationship_history ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.relationship_history (
    id             BIGINT  PRIMARY KEY,
    target_id      TEXT    NOT NULL,
    other_user_id  TEXT    NOT NULL,
    classification TEXT    NOT NULL,
    confidence     REAL    NOT NULL,
    recorded_at    BIGINT  NOT NULL,

    CONSTRAINT fk_rel_history_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_rel_history_pair
    ON public.relationship_history (target_id, other_user_id, recorded_at DESC);

ALTER TABLE public.relationship_history DISABLE ROW LEVEL SECURITY;


-- ── daily_briefs ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.daily_briefs (
    id           BIGINT  PRIMARY KEY,
    target_id    TEXT    NOT NULL,
    date         TEXT    NOT NULL,
    brief_text   TEXT    NOT NULL,
    generated_at BIGINT  NOT NULL,

    CONSTRAINT fk_daily_briefs_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT daily_briefs_unique UNIQUE (target_id, date)
);
CREATE INDEX IF NOT EXISTS idx_daily_briefs_target
    ON public.daily_briefs (target_id, date DESC);

ALTER TABLE public.daily_briefs DISABLE ROW LEVEL SECURITY;


-- ── backfill_progress ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.backfill_progress (
    id                BIGINT  PRIMARY KEY,
    target_id         TEXT    NOT NULL,
    guild_id          TEXT    NOT NULL,
    channel_id        TEXT    NOT NULL,
    status            TEXT    NOT NULL DEFAULT 'pending',
    messages_found    INTEGER NOT NULL DEFAULT 0,
    oldest_message_id TEXT,
    started_at        BIGINT,
    completed_at      BIGINT,
    error             TEXT,

    CONSTRAINT fk_backfill_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT backfill_unique UNIQUE (target_id, channel_id)
);
CREATE INDEX IF NOT EXISTS idx_backfill_target
    ON public.backfill_progress (target_id, status);

ALTER TABLE public.backfill_progress DISABLE ROW LEVEL SECURITY;


-- ── behavioral_baselines ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.behavioral_baselines (
    id               BIGINT  PRIMARY KEY,
    target_id        TEXT    NOT NULL,
    metric_name      TEXT    NOT NULL,
    baseline_value   REAL    NOT NULL,
    std_deviation    REAL    NOT NULL,
    computed_at      BIGINT  NOT NULL,
    data_window_days INTEGER NOT NULL DEFAULT 30,

    CONSTRAINT fk_baselines_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT baselines_unique UNIQUE (target_id, metric_name)
);

ALTER TABLE public.behavioral_baselines DISABLE ROW LEVEL SECURITY;


-- ── target_config ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.target_config (
    target_id                TEXT   PRIMARY KEY,
    social_weight_messages   REAL   NOT NULL DEFAULT 3.0,
    social_weight_reactions  REAL   NOT NULL DEFAULT 1.0,
    social_weight_voice_hours REAL  NOT NULL DEFAULT 5.0,
    social_weight_mentions   REAL   NOT NULL DEFAULT 2.0,
    anomaly_z_threshold      REAL   NOT NULL DEFAULT 2.0,
    updated_at               BIGINT NOT NULL,

    CONSTRAINT fk_target_config_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE public.target_config DISABLE ROW LEVEL SECURITY;


-- ── message_categories ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.message_categories (
    message_id     TEXT    PRIMARY KEY,
    target_id      TEXT    NOT NULL,
    category       TEXT    NOT NULL,
    confidence     REAL    NOT NULL DEFAULT 1.0,
    categorized_at BIGINT  NOT NULL,

    CONSTRAINT fk_msg_cat_target
        FOREIGN KEY (target_id) REFERENCES public.targets (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_msg_cat_target
    ON public.message_categories (target_id, category);

ALTER TABLE public.message_categories DISABLE ROW LEVEL SECURITY;


-- =============================================================================
-- SCHEMA v3 ADDITIONS
-- =============================================================================

-- ── messages — source column (distinguishes live gateway vs backfilled history) ─

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='messages' AND column_name='source') THEN
        ALTER TABLE public.messages ADD COLUMN source TEXT NOT NULL DEFAULT 'live';
    END IF;
END $$;